let bookList = [
    {
        title: "생활코딩! React 리액트 프로그래밍",
        price: 25000,
        author: "이고잉",
        image: "/assets/images/exampleBook.png",
        publicationDate: "2023-02-22",
        publisher: "위키북스",
        salePrice: 12500,
        category: "컴퓨터/IT",
        isbn: "9791158392233",
    },
    {
        title: "생활코딩! React 리액트 프로그래밍",
        price: 25000,
        author: "이고잉",
        image: "/assets/images/exampleBook.png",
        publicationDate: "2023-02-22",
        publisher: "위키북스",
        salePrice: 12500,
        category: "컴퓨터/IT",
        isbn: "9791158392233",
    },
    {
        title: "생활코딩! React 리액트 프로그래밍",
        price: 25000,
        author: "이고잉",
        image: "/assets/images/exampleBook.png",
        publicationDate: "2023-02-22",
        publisher: "위키북스",
        salePrice: 12500,
        category: "컴퓨터/IT",
        isbn: "9791158392233",
    },
    {
        title: "생활코딩! React 리액트 프로그래밍",
        price: 25000,
        author: "이고잉",
        image: "/assets/images/exampleBook.png",
        publicationDate: "2023-02-22",
        publisher: "위키북스",
        salePrice: 12500,
        category: "컴퓨터/IT",
        isbn: "9791158392233",
    },
    {
        title: "생활코딩! React 리액트 프로그래밍",
        price: 25000,
        author: "이고잉",
        image: "/assets/images/exampleBook.png",
        publicationDate: "2023-02-22",
        publisher: "위키북스",
        salePrice: 12500,
        category: "컴퓨터/IT",
        isbn: "9791158392233",
    },
    {
        title: "생활코딩! React 리액트 프로그래밍",
        price: 25000,
        author: "이고잉",
        image: "/assets/images/exampleBook.png",
        publicationDate: "2023-02-22",
        publisher: "위키북스",
        salePrice: 12500,
        category: "컴퓨터/IT",
        isbn: "9791158392233",
    },
    {
        title: "생활코딩! React 리액트 프로그래밍",
        price: 25000,
        author: "이고잉",
        image: "/assets/images/exampleBook.png",
        publicationDate: "2023-02-22",
        publisher: "위키북스",
        salePrice: 12500,
        category: "컴퓨터/IT",
        isbn: "9791158392233",
    },
    {
        title: "생활코딩! React 리액트 프로그래밍",
        price: 25000,
        author: "이고잉",
        image: "/assets/images/exampleBook.png",
        publicationDate: "2023-02-22",
        publisher: "위키북스",
        salePrice: 12500,
        category: "컴퓨터/IT",
        isbn: "9791158392233",
    },
    {
        title: "생활코딩! React 리액트 프로그래밍",
        price: 25000,
        author: "이고잉",
        image: "/assets/images/exampleBook.png",
        publicationDate: "2023-02-22",
        publisher: "위키북스",
        salePrice: 12500,
        category: "컴퓨터/IT",
        isbn: "9791158392233",
    },
];

let postList = [
    {   
        image: "/assets/images/exampleBook.png",
        title: "부는 어디서 오는가",
        content: "1910년 오리지널 초판본 디자인 100년 동안 단 1%만 알았던 부의 법칙 “특정한 방식으로 생각하고, 행동하라” *** 아마존 베스트셀러 최장기 1위 *** *** 전 세계 1억 3천만 부 판매 *** *** 수백만 명의 삶을 바꾼 책 *** “신은 당신을 돕지 않을 수 없다. 신 자신을 위해서라도 그렇게 해야만 하기 때문이다.” 출간 후 백 년이 넘는 기간 동안 1910년 오리지널 초판본 디자인 100년 동안 단 1%만 알았던 부의 법칙 “특정한 방식으로 생각하고, 행동하라” *** 아마존 베스트셀러 최장기 1위 *** *** 전 세계 1억 3천만 부 판매 *** *** 수백만 명의 삶을 바꾼 책 *** “신은 당신을 돕지 않을 수 없다. 신 자신을 위해서라도 그렇게 해야만 하기 때문이다.” 출간 후 백 년이 넘는 기간 동안  ",
    },
    {   
        image: "/assets/images/exampleBook.png",
        title: "[북킴의 Book 리뷰] 김영하, 「살인자의 기억법」",
        content: "안녕하세요! 책의 내용뿐만 아니라 책 구석구석을 톺아보는 북 리뷰어 북킴입니다!! 김영하 작가님의 '살인자의 기억법'입니다. 그렇다면!!! 본격적으로 책을 톺아보도록 합시다!! 책의 표지를 보시면 이런 문구가 적혀 있습니다. 무서운 건 악이 아니오. 시간이지. 아무도 그걸 이길 수가 없거든. 책의 전체적인 내용을 잘 표현한 강력한 문구입니다. 책의 전체적인 내용을 잘 표현한 강력한 문구입니다.책의 전체적인 내용을 잘 표현한 강력한 문구입니다.책의 전체적인 내용을 잘 표현한 강력한 문구입니다. ",
    },
    {   
        image: "/assets/images/exampleBook.png",
        title: "부는 어디서 오는가",
        content: "1910년 오리지널 초판본 디자인 100년 동안 단 1%만 알았던 부의 법칙 “특정한 방식으로 생각하고, 행동하라” *** 아마존 베스트셀러 최장기 1위 *** *** 전 세계 1억 3천만 부 판매 *** *** 수백만 명의 삶을 바꾼 책 *** “신은 당신을 돕지 않을 수 없다. 신 자신을 위해서라도 그렇게 해야만 하기 때문이다.” 출간 후 백 년이 넘는 기간 동안 1910년 오리지널 초판본 디자인 100년 동안 단 1%만 알았던 부의 법칙 “특정한 방식으로 생각하고, 행동하라” *** 아마존 베스트셀러 최장기 1위 *** *** 전 세계 1억 3천만 부 판매 *** *** 수백만 명의 삶을 바꾼 책 *** “신은 당신을 돕지 않을 수 없다. 신 자신을 위해서라도 그렇게 해야만 하기 때문이다.” 출간 후 백 년이 넘는 기간 동안  ",
    },
    {   
        image: "/assets/images/exampleBook.png",
        title: "[북킴의 Book 리뷰] 김영하, 「살인자의 기억법」",
        content: "안녕하세요! 책의 내용뿐만 아니라 책 구석구석을 톺아보는 북 리뷰어 북킴입니다!! 김영하 작가님의 '살인자의 기억법'입니다. 그렇다면!!! 본격적으로 책을 톺아보도록 합시다!! 책의 표지를 보시면 이런 문구가 적혀 있습니다. 무서운 건 악이 아니오. 시간이지. 아무도 그걸 이길 수가 없거든. 책의 전체적인 내용을 잘 표현한 강력한 문구입니다. 책의 전체적인 내용을 잘 표현한 강력한 문구입니다.책의 전체적인 내용을 잘 표현한 강력한 문구입니다.책의 전체적인 내용을 잘 표현한 강력한 문구입니다. ",
    },
    {   
        image: "/assets/images/exampleBook.png",
        title: "부는 어디서 오는가",
        content: "1910년 오리지널 초판본 디자인 100년 동안 단 1%만 알았던 부의 법칙 “특정한 방식으로 생각하고, 행동하라” *** 아마존 베스트셀러 최장기 1위 *** *** 전 세계 1억 3천만 부 판매 *** *** 수백만 명의 삶을 바꾼 책 *** “신은 당신을 돕지 않을 수 없다. 신 자신을 위해서라도 그렇게 해야만 하기 때문이다.” 출간 후 백 년이 넘는 기간 동안 1910년 오리지널 초판본 디자인 100년 동안 단 1%만 알았던 부의 법칙 “특정한 방식으로 생각하고, 행동하라” *** 아마존 베스트셀러 최장기 1위 *** *** 전 세계 1억 3천만 부 판매 *** *** 수백만 명의 삶을 바꾼 책 *** “신은 당신을 돕지 않을 수 없다. 신 자신을 위해서라도 그렇게 해야만 하기 때문이다.” 출간 후 백 년이 넘는 기간 동안  ",
    },
    {   
        image: "/assets/images/exampleBook.png",
        title: "[북킴의 Book 리뷰] 김영하, 「살인자의 기억법」",
        content: "안녕하세요! 책의 내용뿐만 아니라 책 구석구석을 톺아보는 북 리뷰어 북킴입니다!! 김영하 작가님의 '살인자의 기억법'입니다. 그렇다면!!! 본격적으로 책을 톺아보도록 합시다!! 책의 표지를 보시면 이런 문구가 적혀 있습니다. 무서운 건 악이 아니오. 시간이지. 아무도 그걸 이길 수가 없거든. 책의 전체적인 내용을 잘 표현한 강력한 문구입니다. 책의 전체적인 내용을 잘 표현한 강력한 문구입니다.책의 전체적인 내용을 잘 표현한 강력한 문구입니다.책의 전체적인 내용을 잘 표현한 강력한 문구입니다. ",
    },
]
